name: Ping Supabase to Prevent Sleep

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Supabase Health Check
        run: |
          curl -sSf https://YOUR_PROJECT.supabase.co/rest/v1/YOUR_HEALTH_ENDPOINT || echo "Ping failed"
